# Generated by Django 2.2.7 on 2019-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Major', models.CharField(max_length=50)),
                ('Year', models.CharField(max_length=50)),
                ('GPA', models.FloatField()),
            ],
        ),
    ]
