# Generated by Django 2.2.7 on 2019-12-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.IntegerField()),
                ('CourseTitle', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=200)),
                ('CourseSectionCode', models.IntegerField()),
                ('CourseDepartment', models.CharField(max_length=100)),
                ('InstructorFullName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('CourseTitle', models.CharField(max_length=100)),
            ],
        ),
    ]
