# Generated by Django 2.2.7 on 2019-12-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_courses_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='StudentID',
            new_name='LastName',
        ),
    ]
