# Generated by Django 2.2.7 on 2019-12-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0003_auto_20191212_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrollmentdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastName', models.CharField(max_length=100)),
                ('CourseID1', models.CharField(max_length=100)),
                ('CourseID2', models.CharField(max_length=100)),
                ('CourseID3', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='enrollment',
        ),
    ]
