# Generated by Django 2.2.7 on 2019-12-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0004_auto_20191212_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enrollmentdj',
            new_name='enrollment',
        ),
    ]
