# Generated by Django 2.2.7 on 2019-12-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0005_auto_20191212_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='CourseID3',
            new_name='Course3',
        ),
    ]
