# Generated by Django 2.2.7 on 2019-12-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_auto_20191212_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Course3',
            new_name='CourseID3',
        ),
    ]
